export const data = [
  {
    id: 1,
    name: "Cozy Apartment in Downtown",
    address: "123 Main Street, Downtown City, NY 10001",
    image: "https://via.placeholder.com/150?text=House+1",
    tag: "rent",
    amenities: ["Gym", "Pool", "Parking"],
    rating: 4,
    basePrice: 1500,
  },
  {
    id: 2,
    name: "Spacious Family Home",
    address: "456 Elm Street, Suburban Town, CA 90001",
    image: "https://via.placeholder.com/150?text=House+2",
    tag: "buy",
    amenities: ["Backyard", "Playground", "Community Center"],
    rating: 4.5,
    basePrice: 500000,
  },
  {
    id: 3,
    name: "Modern Studio Apartment",
    address: "789 Oak Avenue, Urban Center, TX 75001",
    image: "https://via.placeholder.com/150?text=House+3",
    tag: "commercial",
    amenities: ["High-Speed Internet", "24/7 Security", "On-Site Laundry"],
    rating: 4.2,
    basePrice: 1200,
  },
  {
    id: 4,
    name: "Luxury Villa with Pool",
    address: "321 Pine Drive, Beachside City, FL 33001",
    image: "https://via.placeholder.com/150?text=House+4",
    tag: "rent",
    amenities: ["Private Pool", "Beach Access", "Gourmet Kitchen"],
    rating: 5,
    basePrice: 3000,
  },
  {
    id: 5,
    name: "Charming Cottage",
    address: "654 Maple Lane, Countryside, WA 98001",
    image: "https://via.placeholder.com/150?text=House+5",
    tag: "buy",
    amenities: ["Fireplace", "Garden", "Porch"],
    rating: 4.8,
    basePrice: 350000,
  },
  {
    id: 6,
    name: "Bright Apartment in the Suburbs",
    address: "890 Birch Street, Pleasantville, NJ 08001",
    image: "https://via.placeholder.com/150?text=House+6",
    tag: "commercial",
    amenities: ["Public Transportation", "Shopping Center", "Schools"],
    rating: 4.1,
    basePrice: 1000,
  },
  {
    id: 7,
    name: "Rustic Cabin in the Woods",
    address: "789 Forest Lane, Mountain View, CO 80001",
    image: "https://via.placeholder.com/150?text=House+7",
    tag: "rent",
    amenities: ["Hiking Trails", "Fire Pit", "Mountain Views"],
    rating: 4.9,
    basePrice: 2500,
  },
  {
    id: 8,
    name: "Urban Loft with Skyline View",
    address: "234 Sunset Boulevard, Metropolis, IL 60001",
    image: "https://via.placeholder.com/150?text=House+8",
    tag: "buy",
    amenities: ["Skyline View", "Gym", "Roof Deck"],
    rating: 4.7,
    basePrice: 600000,
  },
  {
    id: 9,
    name: "Victorian-Style Home",
    address: "567 Willow Way, Old Town, MA 01001",
    image: "https://via.placeholder.com/150?text=House+9",
    tag: "commercial",
    amenities: ["Historic District", "Walking Distance to Downtown", "Parking"],
    rating: 4.6,
    basePrice: 450000,
  },
  {
    id: 10,
    name: "Compact Studio for Singles",
    address: "123 Small Street, Compact City, OR 97001",
    image: "https://via.placeholder.com/150?text=House+10",
    tag: "rent",
    amenities: ["Compact Design", "Efficient Appliances", "Central Location"],
    rating: 4.3,
    basePrice: 900,
  },
  {
    id: 11,
    name: "Elegant Penthouse",
    address: "444 Luxury Avenue, Uptown, TX 77001",
    image: "https://via.placeholder.com/150?text=House+11",
    tag: "buy",
    amenities: ["Luxury Finishes", "Private Elevator", "Panoramic Views"],
    rating: 5,
    basePrice: 1000000,
  },
  {
    id: 12,
    name: "Simple Suburban House",
    address: "89 Sunset Drive, Green Valley, MI 49001",
    image: "https://via.placeholder.com/150?text=House+12",
    tag: "commercial",
    amenities: ["Suburban Setting", "Backyard", "Parking"],
    rating: 4.4,
    basePrice: 220000,
  },
  {
    id: 13,
    name: "Small Cottage Near Lake",
    address: "231 Lakeview Road, Lakeside, WI 54001",
    image: "https://via.placeholder.com/150?text=House+13",
    tag: "rent",
    amenities: ["Lake Views", "Fishing", "Boating"],
    rating: 4.8,
    basePrice: 1800,
  },
  {
    id: 14,
    name: "Spacious Ranch House",
    address: "777 Ranch Way, Prairieville, TX 75001",
    image: "https://via.placeholder.com/150?text=House+14",
    tag: "buy",
    amenities: ["Ranch Style", "Large Yard", "Attached Garage"],
    rating: 4.9,
    basePrice: 420000,
  },
  {
    id: 15,
    name: "Downtown Apartment with View",
    address: "567 Skyline Road, Cityscape, NV 89001",
    image: "https://via.placeholder.com/150?text=House+15",
    tag: "commercial",
    amenities: ["Downtown Location", "City Views", "Public Transportation"],
    rating: 4.5,
    basePrice: 2000,
  },
  {
    id: 16,
    name: "Countryside Estate",
    address: "888 Farm Lane, Rolling Hills, KY 40001",
    image: "https://via.placeholder.com/150?text=House+16",
    tag: "rent",
    amenities: ["Countryside Setting", "Private Entrance", "Garden"],
    rating: 4.7,
    basePrice: 2800,
  },
  {
    id: 17,
    name: "Modern Townhouse",
    address: "555 Town Square, Urban Heights, CO 80002",
    image: "https://via.placeholder.com/150?text=House+17",
    tag: "buy",
    amenities: ["Modern Design", "Community Pool", "Fitness Center"],
    rating: 4.8,
    basePrice: 380000,
  },
  {
    id: 18,
    name: "Beachfront Bungalow",
    address: "123 Ocean Drive, Seaside, FL 33002",
    image: "https://via.placeholder.com/150?text=House+18",
    tag: "commercial",
    amenities: ["Beachfront", "Ocean Views", "Private Patio"],
    rating: 5,
    basePrice: 600000,
  },
  {
    id: 19,
    name: "Mountain Retreat",
    address: "999 Alpine Trail, High Point, UT 84001",
    image: "https://via.placeholder.com/150?text=House+19",
    tag: "rent",
    amenities: ["Mountain Views", "Hiking Trails", "Skiing"],
    rating: 4.9,
    basePrice: 3200,
  },
  {
    id: 20,
    name: "Cozy Urban Apartment",
    address: "111 Main Avenue, City Center, NY 10002",
    image: "https://via.placeholder.com/150?text=House+20",
    tag: "buy",
    amenities: ["Urban Location", "Public Transportation", "Gym"],
    rating: 4.6,
    basePrice: 300000,
  },
  {
    id: 21,
    name: "Luxury City Apartment",
    address: "222 Central Boulevard, Urban Core, TX 77002",
    image: "https://via.placeholder.com/150?text=House+21",
    tag: "commercial",
    amenities: ["Luxury Finishes", "City Views", "24/7 Concierge"],
    rating: 5,
    basePrice: 400000,
  },
  {
    id: 22,
    name: "Quiet Suburban Home",
    address: "333 Elmwood Drive, Peaceful Town, CA 94001",
    image: "https://via.placeholder.com/150?text=House+22",
    tag: "rent",
    amenities: ["Suburban Setting", "Quiet Neighborhood", "Backyard"],
    rating: 4.5,
    basePrice: 2200,
  },
  {
    id: 23,
    name: "Lakeside Cottage",
    address: "444 Waterway Lane, Lakeview, WI 53001",
    image: "https://via.placeholder.com/150?text=House+23",
    tag: "buy",
    amenities: ["Lakeside Location", "Fishing", "Boating"],
    rating: 4.8,
    basePrice: 320000,
  },
  {
    id: 24,
    name: "Studio in Art District",
    address: "555 Creative Street, Artsy City, OR 97002",
    image: "https://via.placeholder.com/150?text=House+24",
    tag: "commercial",
    amenities: [
      "Art District Location",
      "Public Transportation",
      "Coffee Shops",
    ],
    rating: 4.4,
    basePrice: 1800,
  },
  {
    id: 25,
    name: "Riverside Villa",
    address: "666 River Drive, Flowing Town, TN 37001",
    image: "https://via.placeholder.com/150?text=House+25",
    tag: "rent",
    amenities: ["Riverside Location", "Private Patio", "Fishing"],
    rating: 4.9,
    basePrice: 3500,
  },
  {
    id: 26,
    name: "Open-Concept Loft",
    address: "777 Open Street, Trendy City, NY 10003",
    image: "https://via.placeholder.com/150?text=House+26",
    tag: "buy",
    amenities: ["Open Concept", "High Ceilings", "Exposed Brick"],
    rating: 4.7,
    basePrice: 500000,
  },
  {
    id: 27,
    name: "Cabin in the Hills",
    address: "888 Woodland Trail, Quiet Valley, VA 22001",
    image: "https://via.placeholder.com/150?text=House+27",
    tag: "commercial",
    amenities: ["Hillside Location", "Private Entrance", "Hiking Trails"],
    rating: 4.6,
    basePrice: 280000,
  },
  {
    id: 28,
    name: "Urban High-Rise Condo",
    address: "999 Tower Road, Sky City, IL 60002",
    image: "https://via.placeholder.com/150?text=House+28",
    tag: "rent",
    amenities: ["High-Rise Views", "Gym", "Pool"],
    rating: 4.8,
    basePrice: 2500,
  },
  {
    id: 29,
    name: "Family-Friendly Home",
    address: "1010 Neighborhood Lane, Suburban Bliss, CA 90002",
    image: "https://via.placeholder.com/150?text=House+29",
    tag: "buy",
    amenities: ["Family-Friendly", "Backyard", "Playground"],
    rating: 4.9,
    basePrice: 450000,
  },
  {
    id: 30,
    name: "Luxury Retreat",
    address: "1111 Paradise Lane, Exclusive Estates, FL 33003",
    image: "https://via.placeholder.com/150?text=House+30",
    tag: "commercial",
    amenities: ["Luxury Finishes", "Private Pool", "Gourmet Kitchen"],
    rating: 5,
    basePrice: 800000,
  },
];
